// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2core.Models;

namespace WebApplication2core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication2core.Models.Cart", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("customerid");

                    b.Property<double>("grandTotal");

                    b.HasKey("id");

                    b.HasIndex("customerid");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WebApplication2core.Models.CartProduct", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("cart_id");

                    b.Property<long?>("cartid");

                    b.Property<long>("product_id");

                    b.Property<long?>("productid");

                    b.HasKey("id");

                    b.HasIndex("cartid");

                    b.HasIndex("productid");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("WebApplication2core.Models.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplication2core.Models.Customer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApplication2core.Models.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("category_id");

                    b.Property<long?>("categoryid");

                    b.Property<string>("content");

                    b.Property<string>("name");

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApplication2core.Models.Cart", b =>
                {
                    b.HasOne("WebApplication2core.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerid");
                });

            modelBuilder.Entity("WebApplication2core.Models.CartProduct", b =>
                {
                    b.HasOne("WebApplication2core.Models.Cart", "cart")
                        .WithMany("cartProducts")
                        .HasForeignKey("cartid");

                    b.HasOne("WebApplication2core.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid");
                });

            modelBuilder.Entity("WebApplication2core.Models.Product", b =>
                {
                    b.HasOne("WebApplication2core.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryid");
                });
#pragma warning restore 612, 618
        }
    }
}
